### ISSUE TITLE
Mod suggestion: NetherEx port.

### ISSUE THREAD

**Issue by MagmaSlime123** [martmists-gh/fabric-mod-wishlist#32]
### Description
A Nether expansion mod.

### Details

- Does a Forge version of this mod exist? Yes
    - If yes, what is the link to the github/curseforge? [netherex](https://www.curseforge.com/minecraft/mc-mods/netherex)
- Does a Fabric version of this mod exist for an older MC version? No

**Comment by Martmists-GH** [comment]
Cinderscapes and Better Nether should cover this.

**Comment by ehx-v1** [comment]
I disagree with the closing reason. While Cinderscapes and Better Nether both fulfill the same role as NetherEx, each of the mods takes a different approach at it, so having all of them would enhance the variety. It's like saying Addendum shouldn't have been implemented because Endergetic Expansion already existed.

**Comment by MagmaSlime123** [comment]
And both are on Fabric.

**Comment by ehx-v1** [comment]
That's not my point. As I said, they fulfill the same general role (enhancing the Nether), but in a vastly different way. Another example this compares to is how BOP relates to BYG.

Some, like you, are OK with switching to Cinderscapes and Better Nether. Others would prefer the way NetherEx does it. If the list is meant to display the community's desires for the Fabric mod landscape, NetherEx deserves a place on it.
